# docker-compose.yml
# @see https://stackoverflow.com/questions/26598738/how-to-create-user-database-in-script-for-docker-postgres
version: '3.8'
services:
  database:
    build:
      context: .
      dockerfile: ./db/db.Dockerfile
    restart: always
    ports:
      # <Port exposed> : < Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
    networks:
    - backend_network
    env_file:
      - ./db/db.env # configure postgres
    
    volumes:
      - postgis-database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: karl.sangabriel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: a1128f69-e6f7-4e93-a2df-3d4db6030abc
    ports:
    - "8889:80"
    networks:
    - backend_network
    env_file:
      - ./db/db.env # configure postgres
networks:
  backend_network:
    driver: bridge

volumes:
  postgis-database-data: # named volumes can be managed easier using docker-compose